# The single line to change when moving to BioHPC
data_root: "C:\\Users\\gerit\\projects\\lab4-methods-mining-data"

zotero:
  collection_name: "pubmed-LosonczyA-set"

target_authors:
  # Add the full list of authors whose pipelines you're extracting
  - "Gergely F Turi"
  - "Asako Noguchi"
  - "Hyun Choong Yong"
  - "Jingcheng Shi"
  - "Eunji Kong"
  - "Stephanie A Herrlinger"
  - "Kevin C Gonzalez"
  - "Justin K O'Hare"
  - "John C Bowler"
  - "Satoshi Terada"
  - "Zhenrui Liao"
  - "Wenke Li"
  - "Bert Vancura"
  - "Tristan Geiller"
  - "Sebnem N Tuncdemir"
  - "Andres D Grosmark"
  - "Sebi V Rolotti"
  - "James B Priestley"
  - "Fraser T Sparks"
  - "Barna Dudok"
  - "Alexandra Mansell Kaufman"
  - "Mohsin S Ahmed"
  - "Jeffrey D Zaremba"
  - "Nathan B Danielson"
  - "Tommy L Jr Lewis"
  - "Patrick Kaifosh"
  - "Matthew Lovett-Barron"
  # - ...

extraction:
  confidence_levels: ["high", "medium", "low"]
  attribution_tiers:
    - "author_contributions_statement"
    - "methods_text_inference"
    - "position_heuristic"
